apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
	app: app
    spec:
      containers:
      - name: app
        image: 253490784255.dkr.ecr.ap-south-1.amazonaws.com/app:latest
        ports:
	- containerPort: 80



